kind: ActiveMQArtemis
apiVersion: broker.amq.io/v1beta1
metadata:
  name: broker-amq-mqtt
  namespace: default
spec:
  deploymentPlan:
    image: placeholder
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 2
  console:
    expose: true
  acceptors:
    - name: all
      port: 61616
      expose: true