kind: Secret
apiVersion: v1
metadata:
  name: iot-kafka2s3-secret
type: Opaque  
data:
  application.properties: |
    ICBzMy5hY2Nlc3NLZXk6IHVPQ1BjTXhmRXlLV01Ub3hPYkJyCiAgczMuc2VjcmV0S2V5OiAveFFqWG8waXRCdGgxT2lpT0swME9PL2NPNXhSVnQ4ek1wMUx1ZDBz