apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-kafka2s3-config
data:
  application.properties: |
    
    kafka.broker.uri=manuela-kafka-cluster-kafka-bootstrap:9092
    kafka.broker.topic.temperature=iot-sensor-sw-temperature
    kafka.broker.topic.vibration=iot-sensor-sw-vibration

    s3.region=
    s3.bucket.name=s3-local-bc3276b2-c8a6-426d-8b39-75fef36bef8f
    s3.message.aggregation.count=10
    s3.custom.endpoint.enabled=true
    s3.custom.endpoint.url=s3.openshift-storage.svc

    