apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
spec:
  channel: stable-4.13
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: odf-operator.v4.13.0-rhodf